#!/usr/bin/env python3
"""Generate src/boards.s from the captured reference maps.

Reads reference/maps/boardNN.txt (11 rows of 20 checklist letters,
written by tools/atari_boards_decode.py) and boardNN_units.txt
("SIDE CLASS x y" lines) for NN = 01..10 and writes a Merlin source
with, for each board, the 220-character map that board_load_text
decodes and the starting unit list that setup_game feeds to
unit_add. Boards missing from reference/maps/ get an empty entry
(a zero pointer) so the build still works while the capture is in
progress; --strict fails instead.

Usage:
    python3 tools/gen_boards.py [--maps reference/maps] [--out src/boards.s] [--strict]
"""
import argparse
import os
import sys

NUM_BOARDS = 10
LETTERS = set(".T~=Mwygpb")


def read_board(maps, n):
    path = os.path.join(maps, f"board{n:02d}.txt")
    if not os.path.exists(path):
        return None
    rows = [l.rstrip("\n") for l in open(path) if l.strip()]
    if len(rows) != 11 or any(len(r) != 20 for r in rows):
        raise SystemExit(f"{path}: expected 11 rows of 20 characters")
    bad = {c for r in rows for c in r} - LETTERS
    if bad:
        raise SystemExit(f"{path}: unknown map letters {sorted(bad)}")
    units = []
    upath = os.path.join(maps, f"board{n:02d}_units.txt")
    if os.path.exists(upath):
        for line in open(upath):
            line = line.split("#")[0].strip()
            if line:
                side, cls, x, y = line.split()
                units.append((side, cls, int(x), int(y)))
    return rows, units


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--maps", default=os.path.join(os.path.dirname(__file__), "..", "reference", "maps"))
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "src", "boards.s"))
    ap.add_argument("--strict", action="store_true")
    a = ap.parse_args()
    boards = {}
    for n in range(1, NUM_BOARDS + 1):
        b = read_board(a.maps, n)
        if b is None and a.strict:
            raise SystemExit(f"board {n} is missing from {a.maps}")
        boards[n] = b
    out = []
    w = out.append
    w("*----------------------------------------------------------")
    w("* boards.s - The ten original boards and their starting")
    w("* positions, GENERATED by tools/gen_boards.py from")
    w("* reference/maps/. Do not edit; re-run the generator.")
    w("*")
    w("* board_map_ptrs[n-1] -> 220 map letters (board_load_text)")
    w("* board_units_ptrs[n-1] -> side, class, x, y records, $FF end")
    w("* A zero pointer means the board has not been captured yet.")
    w("*----------------------------------------------------------")
    w(f"NUM_BOARDS = {NUM_BOARDS}")
    w("")
    w("board_map_ptrs")
    for n in range(1, NUM_BOARDS + 1):
        w(f" da {'board_map_%d' % n if boards[n] else '0'}")
    w("board_units_ptrs")
    for n in range(1, NUM_BOARDS + 1):
        w(f" da {'board_units_%d' % n if boards[n] else '0'}")
    for n in range(1, NUM_BOARDS + 1):
        if not boards[n]:
            continue
        rows, units = boards[n]
        w("")
        w(f"* Board {n}")
        w(f"board_map_{n}")
        for r in rows:
            w(f" asc '{r}'")
        w(f"board_units_{n}")
        for side, cls, x, y in units:
            w(f" dfb {side},{cls},{x},{y}")
        w(" dfb $FF")
    open(a.out, "w").write("\n".join(out) + "\n")
    have = [n for n in boards if boards[n]]
    print(f"wrote {a.out}: boards {have}" + ("" if len(have) == NUM_BOARDS else f" (missing {[n for n in boards if not boards[n]]})"))


if __name__ == "__main__":
    main()
