#!/usr/bin/env python3
"""Generate src/board_art.s, the board artwork carried over from the
Atari original (milestone 4):

- board_charset: the 64 glyphs of the game's character set ($9800,
  reference/raw/boards/board_charset.bin, the same on every board);
- board_look_N and board_look_ptrs: each board's 220 screen codes as
  captured (colour register in bits 6-7, glyph in bits 0-5), the
  look of every square, from reference/raw/boards/boardNN_codes.txt;
- board_palettes: each board's COLBK and COLPF0-3 as IIGS 12-bit
  colours, measured from the capture PNGs' palettes;
- art_tbl: the renderer's nibble table, four bytes of super hi-res
  pixels for every 4-pixel glyph slice in every glyph colour, on the
  background slot.

Usage: python3 tools/gen_board_art.py   (a Makefile rule)
"""
import json
import os
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS)
from atari_shot import read_image  # noqa: E402

REPO = os.path.abspath(os.path.join(TOOLS, ".."))
RAW = os.path.join(REPO, "reference", "raw", "boards")
OUT = os.path.join(REPO, "src", "board_art.s")
NUM_BOARDS = 10
SLOT_BK, SLOT_PF0 = 1, 2           # palette slots: background, then colour registers 0-3


def hexlines(f, data, per_line=32):
    for i in range(0, len(data), per_line):
        f.write(" hex " + data[i:i + per_line].hex().upper() + "\n")


def main():
    charset = open(os.path.join(RAW, "board_charset.bin"), "rb").read()[:512]
    caps = json.load(open(os.path.join(RAW, "boards_capture.json")))
    with open(OUT, "w") as f:
        f.write("*----------------------------------------------------------\n")
        f.write("* board_art.s - The original's board character set, each\n")
        f.write("* board's look (captured screen codes) and colours, and the\n")
        f.write("* renderer's nibble table. GENERATED by tools/gen_board_art.py\n")
        f.write("* from reference/raw/boards/; do not edit, re-run the generator.\n")
        f.write("*----------------------------------------------------------\n")
        f.write(f"ART_SLOT_BK  = {SLOT_BK}             ; palette slot of the board's background\n")
        f.write(f"ART_SLOT_PF0 = {SLOT_PF0}             ; colour register n -> slot ART_SLOT_PF0+n\n\n")
        f.write("* 64 glyphs of 8 rows, 8 x 8 Atari pixels each\n")
        f.write("board_charset\n")
        hexlines(f, charset)
        f.write("\n* COLBK, COLPF0-3 per board as IIGS colours\n")
        f.write("board_palettes\n")
        for n in range(1, NUM_BOARDS + 1):
            cols = caps[str(n)]["colours"]
            pal = read_image(os.path.join(RAW, f"board{n:02d}.png"))[3]
            words, atari = [], []
            for reg in ("COLBK", "COLPF0", "COLPF1", "COLPF2", "COLPF3"):
                c = int(cols[reg], 16)
                r, g, b = pal[c]
                words.append(f"${r // 17:X}{g // 17:X}{b // 17:X}")
                atari.append(f"${c:02X}")
            f.write(" dw " + ",".join(words) + f"   ; board {n}: Atari " + " ".join(atari) + "\n")
        f.write("\n* Each board's 220 screen codes, row by row\n")
        f.write("board_look_ptrs\n")
        for n in range(1, NUM_BOARDS + 1):
            f.write(f" da board_look_{n}\n")
        for n in range(1, NUM_BOARDS + 1):
            f.write(f"board_look_{n}\n")
            for line in open(os.path.join(RAW, f"board{n:02d}_codes.txt")):
                codes = bytes((int(c, 16) << 6) | int(g, 16) for c, g in (t.split(":") for t in line.split()))
                assert len(codes) == 20
                f.write(" hex " + codes.hex().upper() + "\n")
        f.write("\n* art_tbl: for glyph colour f (0-3) and a 4-pixel slice n\n")
        f.write("* (0-15, leftmost pixel in bit 3), the four screen bytes at\n")
        f.write("* f*64+n*4: a glyph pixel is two super hi-res pixels of slot\n")
        f.write("* ART_SLOT_PF0+f, a background pixel two of slot ART_SLOT_BK.\n")
        f.write("art_tbl\n")
        for fg in range(4):
            slot = SLOT_PF0 + fg
            row = bytes()
            for nib in range(16):
                row += bytes((slot * 17) if nib & (8 >> i) else (SLOT_BK * 17) for i in range(4))
            hexlines(f, row, 32)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
