#!/usr/bin/env python3
"""Render a captured Atari mode-7 picture into an Apple IIGS super
hi-res bitmap as a Merlin data file. Generalises
tools/gen_title_art.py: the title plaque and the STATUS plaque are
both rows of 20 mode-7 codes drawn through a character set, and the
IIGS shows each 8 x 8 glyph as 16 x 16 pixels, so a row is 320 x 16.

Slots: each Atari colour source (background, colour registers 0-3)
is written as an IIGS palette slot index you choose with --slots, so
a picture can share the palette of the screen it appears on, and a
register whose colour the original changes at run time (the tank on
the status screen is red or black by side) gets a slot the code can
repaint.

Usage:
    python3 tools/gen_plaque.py --codes CODES.bin --rows N
        --charset CHARSET.bin | --charset-ram RAM.dat --chbase 0x9A00
        --slots BG,C0,C1,C2,C3 --label status --out src/status_art.s
        [--palette-png SHOT.png --info INFO.json --preview OUT.png --scale 2]

--palette-png and --info (colours_shadow) are only needed for the
preview, which shows the picture in the capture's real colours.
"""
import argparse
import json
import os
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS)
from atari_shot import read_image, write_png  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--codes", required=True)
    ap.add_argument("--rows", type=int, required=True)
    ap.add_argument("--charset", help="1 KB character set file")
    ap.add_argument("--charset-ram", help="or a RAM dump...")
    ap.add_argument("--chbase", type=lambda s: int(s, 0), help="...and the character set address in it")
    ap.add_argument("--slots", required=True, help="IIGS slot for background,colour0,colour1,colour2,colour3")
    ap.add_argument("--label", required=True, help="symbol prefix, e.g. status -> status_art, STATUS_ART_ROWS")
    ap.add_argument("--out", required=True)
    ap.add_argument("--palette-png")
    ap.add_argument("--info")
    ap.add_argument("--preview")
    ap.add_argument("--scale", type=int, default=2)
    a = ap.parse_args()

    codes = open(a.codes, "rb").read()[:a.rows * 20]
    if a.charset:
        charset = open(a.charset, "rb").read()[:1024]
    else:
        ram = open(a.charset_ram, "rb").read()
        charset = ram[a.chbase:a.chbase + 1024]
    slots = [int(s) for s in a.slots.split(",")]
    assert len(slots) == 5 and all(0 <= s < 16 for s in slots)

    rows = []
    for cy in range(a.rows):
        for by in range(8):
            line = []
            for cx in range(20):
                code = codes[cy * 20 + cx]
                colour, glyph = code >> 6, code & 0x3F
                bits = charset[glyph * 8 + by]
                for bx in range(8):
                    slot = slots[colour + 1] if bits & (0x80 >> bx) else slots[0]
                    line += [slot, slot]
            rows.append(line)
            rows.append(list(line))
    height = a.rows * 16
    sym = a.label
    with open(a.out, "w") as f:
        f.write("*----------------------------------------------------------\n")
        f.write(f"* {os.path.basename(a.out)} - captured Atari picture as a 320 x {height}\n")
        f.write("* super hi-res bitmap, GENERATED by tools/gen_plaque.py. Do not\n")
        f.write("* edit; re-run the generator (see the Makefile).\n")
        f.write(f"* Slots: background {slots[0]}, colour registers 0-3 -> {slots[1:]}\n")
        f.write("*----------------------------------------------------------\n")
        f.write(f"{sym.upper()}_ART_ROWS = {height}\n")
        f.write(f"{sym}_art\n")
        for line in rows:
            packed = bytes((line[i] << 4) | line[i + 1] for i in range(0, 320, 2))
            for i in range(0, 160, 32):
                f.write(" hex " + packed[i:i + 32].hex().upper() + "\n")
    print(f"wrote {a.out}: {height} rows as {sym}_art, slots {slots}")

    if a.preview:
        pal = read_image(a.palette_png)[3] if a.palette_png else None
        shadows = [int(c.strip("$"), 16) for c in json.load(open(a.info))["colours_shadow"]] if a.info else None
        rgb_by_slot = {}
        if pal and shadows:
            atari = [shadows[4]] + shadows[:4]
            for s, c in zip(slots, atari):
                rgb_by_slot[s] = tuple(pal[c])
        s = a.scale
        out_rows = []
        for line in rows:
            px = b"".join(bytes(rgb_by_slot.get(v, (v * 16, v * 16, v * 16))) * s for v in line)
            out_rows.extend([px] * s)
        write_png(a.preview, 320 * s, height * s, out_rows)
        print("preview:", a.preview)


if __name__ == "__main__":
    main()
