#!/usr/bin/env python3
"""Render the Atari title plaque (the tank with COMBAT CHESS) into an
Apple IIGS super hi-res bitmap, from the capture in
reference/raw/title/: six rows of 20 ANTIC mode-7 codes
(title_plaque.bin), the character set they index (title_charset.bin)
and the colour registers (title_info.json), with exact RGB from the
screenshot's palette (title.png).

Mode 7 draws each 8 x 8 glyph as 16 x 16 screen pixels in one of four
colours chosen by bits 6-7 of the code, over the background. In 320
mode one IIGS pixel is one Atari colour clock, so a mode-7 pixel is
2 x 2 IIGS pixels and the plaque is exactly 320 x 96.

Writes:
    src/title_art.s     TITLE_ART_ROWS, title_palette (4 entries as
                        $0RGB words for palette slots 0-3), and
                        title_art: 96 rows x 160 bytes, two 4-bit
                        pixels per byte, slot 0 = background
    OUT.png (optional)  preview at --scale

Usage: python3 tools/gen_title_art.py [--preview OUT.png --scale 2]
"""
import argparse
import json
import os
import struct
import sys
import zlib

TOOLS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, TOOLS)
from atari_shot import read_image, write_png  # noqa: E402

REPO = os.path.abspath(os.path.join(TOOLS, ".."))
RAW = os.path.join(REPO, "reference", "raw", "title")


def rgb_to_iigs(rgb):
    """8-bit RGB -> $0RGB with 4 bits per channel."""
    r, g, b = (c >> 4 for c in rgb)
    return (r << 8) | (g << 4) | b


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(REPO, "src", "title_art.s"))
    ap.add_argument("--preview")
    ap.add_argument("--scale", type=int, default=2)
    a = ap.parse_args()

    plaque = open(os.path.join(RAW, "title_plaque.bin"), "rb").read()
    charset = open(os.path.join(RAW, "title_charset.bin"), "rb").read()
    info = json.load(open(os.path.join(RAW, "title_info.json")))
    shadows = [int(c.strip("$"), 16) for c in info["colours_shadow"]]   # COLOR0-3, COLOR4 = background
    pal256 = read_image(os.path.join(RAW, "title.png"))[3]
    # IIGS slots: 0 background, 1-4 colour registers 0-3
    atari_codes = [shadows[4]] + shadows[:4]
    slot_rgb = [tuple(pal256[c]) for c in atari_codes]

    rows = []                                    # 96 rows of 320 slot indices
    for cy in range(6):
        for by in range(8):
            line = []
            for cx in range(20):
                code = plaque[cy * 20 + cx]
                colour, glyph = code >> 6, code & 0x3F
                bits = charset[glyph * 8 + by]
                for bx in range(8):
                    slot = colour + 1 if bits & (0x80 >> bx) else 0
                    line += [slot, slot]                 # 2 pixels wide
            rows.append(line)
            rows.append(list(line))                      # 2 rows tall
    assert len(rows) == 96 and all(len(r) == 320 for r in rows)

    with open(a.out, "w") as f:
        f.write("*----------------------------------------------------------\n")
        f.write("* title_art.s - The Atari title plaque as a 320 x 96 super\n")
        f.write("* hi-res bitmap, GENERATED by tools/gen_title_art.py from\n")
        f.write("* reference/raw/title/. Do not edit; re-run the generator.\n")
        f.write("*\n")
        f.write("* title_palette: 5 words, $0RGB, for palette slots 0-4\n")
        f.write("*   (0 = background, 1-4 = Atari colour registers 0-3)\n")
        f.write("* title_art: TITLE_ART_ROWS rows of 160 bytes, two 4-bit\n")
        f.write("*   pixels per byte, high nibble left, slot indices 0-4\n")
        f.write("*----------------------------------------------------------\n")
        f.write("TITLE_ART_ROWS = 96\n")
        f.write("title_palette\n dw " + ",".join(f"${rgb_to_iigs(c):04X}" for c in slot_rgb) + "\n")
        f.write("title_art\n")
        for line in rows:
            packed = bytes((line[i] << 4) | line[i + 1] for i in range(0, 320, 2))
            for i in range(0, 160, 32):
                f.write(" hex " + packed[i:i + 32].hex().upper() + "\n")
    print(f"wrote {a.out}: 96 rows, palette "
          + " ".join(f"${c:02X}->${rgb_to_iigs(rgb):03X}" for c, rgb in zip(atari_codes, slot_rgb)))

    if a.preview:
        s = a.scale
        out_rows = []
        for line in rows:
            px = b"".join(bytes(slot_rgb[v]) * s for v in line)
            out_rows.extend([px] * s)
        write_png(a.preview, 320 * s, 96 * s, out_rows)
        print("preview:", a.preview)


if __name__ == "__main__":
    main()
