*----------------------------------------------------------
* boards.s - The ten original boards and their starting
* positions, GENERATED by tools/gen_boards.py from
* reference/maps/. Do not edit; re-run the generator.
*
* board_map_ptrs[n-1] -> 220 map letters (board_load_text)
* board_units_ptrs[n-1] -> side, class, x, y records, $FF end
* A zero pointer means the board has not been captured yet.
*----------------------------------------------------------
NUM_BOARDS = 10

board_map_ptrs
 da board_map_1
 da board_map_2
 da board_map_3
 da board_map_4
 da board_map_5
 da board_map_6
 da board_map_7
 da board_map_8
 da board_map_9
 da board_map_10
board_units_ptrs
 da board_units_1
 da board_units_2
 da board_units_3
 da board_units_4
 da board_units_5
 da board_units_6
 da board_units_7
 da board_units_8
 da board_units_9
 da board_units_10

* Board 1
board_map_1
 asc 'TTTTTTT~TTT.MM...TTT'
 asc 'TTTTT.=~T.MMMMTTT.TT'
 asc 'TTTT.T~=.MMMMTTTTT.T'
 asc 'TTT.TT~T.MMMMTTTTT.T'
 asc 'TTT.TT~~~.MMMTTTTT.T'
 asc 'TTTT.TTT~=MMMMTTT.TT'
 asc 'MTTTT...=~MMMMTT.TTT'
 asc 'MMTTTT.TT~~~~~T.TTTT'
 asc 'MMMTTTT.TTT~~~=TTTTT'
 asc 'MMMMTTTT.TTTT=~TTTTT'
 asc 'MMMMMTTTT....T~~TTTT'
board_units_1
 dfb SIDE_RED,CLASS_CRUISER,1,0
 dfb SIDE_RED,CLASS_TANK,2,0
 dfb SIDE_RED,CLASS_CAR,3,0
 dfb SIDE_RED,CLASS_CAR,1,1
 dfb SIDE_RED,CLASS_TANK,2,1
 dfb SIDE_RED,CLASS_CAR,3,1
 dfb SIDE_RED,CLASS_CAR,2,2
 dfb SIDE_BLACK,CLASS_CAR,18,7
 dfb SIDE_BLACK,CLASS_TANK,19,7
 dfb SIDE_BLACK,CLASS_TANK,17,8
 dfb SIDE_BLACK,CLASS_CAR,18,8
 dfb SIDE_BLACK,CLASS_CAR,19,8
 dfb SIDE_BLACK,CLASS_CAR,16,9
 dfb SIDE_BLACK,CLASS_CAR,17,9
 dfb SIDE_BLACK,CLASS_CRUISER,19,9
 dfb SIDE_BLACK,CLASS_TANK,17,10
 dfb $FF

* Board 2
board_map_2
 asc '~~~...~~~~.......~~~'
 asc '~~.TTT.~~=TTT.....~~'
 asc '~...TTT.=~~TTTT...~~'
 asc '....TTTT~~~TTTTT.~~~'
 asc '.TTTTTT~~~TTTT.=~~~~'
 asc '.TTTTT=~~TTTT.~~=~~~'
 asc '..TTTT~=TTTT~~~~TT.~'
 asc '.TTTT~~~=~~~~~~TTTT.'
 asc 'T.TT~~~=~~~~T~TTTT..'
 asc '~TTT=~TTT~~TTTTTT..~'
 asc '~~T~~=TTTTTTTTTT..~~'
board_units_2
 dfb SIDE_RED,CLASS_CAR,3,1
 dfb SIDE_RED,CLASS_CAR,2,2
 dfb SIDE_RED,CLASS_TANK,3,2
 dfb SIDE_RED,CLASS_CAR,4,2
 dfb SIDE_RED,CLASS_TANK,1,3
 dfb SIDE_RED,CLASS_CRUISER,3,3
 dfb SIDE_RED,CLASS_CAR,1,4
 dfb SIDE_BLACK,CLASS_CAR,15,8
 dfb SIDE_BLACK,CLASS_CAR,16,8
 dfb SIDE_BLACK,CLASS_CAR,17,8
 dfb SIDE_BLACK,CLASS_CAR,14,9
 dfb SIDE_BLACK,CLASS_TANK,16,9
 dfb SIDE_BLACK,CLASS_TANK,17,9
 dfb SIDE_BLACK,CLASS_CAR,13,10
 dfb SIDE_BLACK,CLASS_TANK,14,10
 dfb SIDE_BLACK,CLASS_CRUISER,16,10
 dfb $FF

* Board 3
board_map_3
 asc 'MMMMMMT~TTMMMMMMMMMM'
 asc 'MMMMMTT~TTTMMMMMMMMM'
 asc 'MMMMMTT~~TT.MMMMMMMM'
 asc 'MMMMMTTT~~TT..MMMMMM'
 asc 'MMMMM..TT~TT...MMMMM'
 asc 'MMMMM..TT~TT...MMMMM'
 asc 'MMMMM..T~~TT...MMMMM'
 asc 'MMMMM..T~TTTT.TMMMMM'
 asc 'MMMMM..T~~~~TTTMMMMM'
 asc 'MMMMMMTTTTT~TTMMMMMM'
 asc 'MMMMMMMTTTT~~MMMMMMM'
board_units_3
 dfb SIDE_RED,CLASS_CAR,11,2
 dfb SIDE_RED,CLASS_CAR,12,3
 dfb SIDE_RED,CLASS_TANK,13,3
 dfb SIDE_BLACK,CLASS_CAR,5,4
 dfb SIDE_BLACK,CLASS_TANK,6,4
 dfb SIDE_RED,CLASS_CAR,12,4
 dfb SIDE_RED,CLASS_TANK,13,4
 dfb SIDE_RED,CLASS_CRUISER,14,4
 dfb SIDE_BLACK,CLASS_CAR,5,5
 dfb SIDE_BLACK,CLASS_CAR,6,5
 dfb SIDE_RED,CLASS_CAR,12,5
 dfb SIDE_BLACK,CLASS_CRUISER,5,6
 dfb SIDE_BLACK,CLASS_TANK,6,6
 dfb SIDE_BLACK,CLASS_TANK,5,7
 dfb SIDE_BLACK,CLASS_CAR,6,7
 dfb SIDE_BLACK,CLASS_CAR,5,8
 dfb $FF

* Board 4
board_map_4
 asc '~~~~~TTTTTTTTTTTTTTT'
 asc 'T~~T~~~~~T......TTTT'
 asc 'TT~TMM..~=.TTTT...TT'
 asc 'TT~..MM.=~~~~TTTT...'
 asc 'TT~~~.MM.~~T~~~~TT..'
 asc '.TTT~.TMMM.TT~~~~~T.'
 asc '...=~.TTMMM.T~TTT~=.'
 asc '..T~=.TT.MMT~~TT.=~T'
 asc '.TT~~~~~~~~T~~TT..~~'
 asc '..TTT~~TTT~~~T...TTT'
 asc '................TTTT'
board_units_4
 dfb SIDE_RED,CLASS_TANK,7,0
 dfb SIDE_RED,CLASS_CAR,9,0
 dfb SIDE_RED,CLASS_CAR,10,0
 dfb SIDE_RED,CLASS_TANK,11,0
 dfb SIDE_RED,CLASS_CRUISER,9,1
 dfb SIDE_RED,CLASS_CAR,11,1
 dfb SIDE_BLACK,CLASS_TANK,1,2
 dfb SIDE_RED,CLASS_CAR,10,2
 dfb SIDE_BLACK,CLASS_TANK,0,3
 dfb SIDE_BLACK,CLASS_CAR,1,3
 dfb SIDE_BLACK,CLASS_TANK,0,4
 dfb SIDE_BLACK,CLASS_CRUISER,1,4
 dfb SIDE_BLACK,CLASS_CAR,0,5
 dfb SIDE_BLACK,CLASS_CAR,1,5
 dfb SIDE_BLACK,CLASS_CAR,2,5
 dfb SIDE_BLACK,CLASS_CAR,0,6
 dfb $FF

* Board 5
board_map_5
 asc 'TTTTTTTTTTT..~TTTTTT'
 asc 'TTTTTTTTTTT.~~TTTTTT'
 asc 'TTTMMMMTTTT.~=.TTTTT'
 asc 'TTTMMMMMMTT.=~..TTTT'
 asc 'TTTMMMMMMMT~~~.MMTTT'
 asc 'TTTTMMMMMM=~TTMMMTTT'
 asc 'TTTTTMMMM.~=.MMMTTTT'
 asc 'TTTTTMMMM.~~.MMMTTTT'
 asc '.TTTTTMMM..~=.TTTTTT'
 asc '..TTTT.....=~TTTTTTT'
 asc '.......TTTTT~~TTTTTT'
board_units_5
 dfb SIDE_RED,CLASS_CAR,1,0
 dfb SIDE_RED,CLASS_CAR,1,1
 dfb SIDE_RED,CLASS_CAR,2,1
 dfb SIDE_RED,CLASS_TANK,3,1
 dfb SIDE_RED,CLASS_TANK,1,2
 dfb SIDE_RED,CLASS_CRUISER,2,2
 dfb SIDE_RED,CLASS_CAR,1,3
 dfb SIDE_BLACK,CLASS_TANK,17,4
 dfb SIDE_BLACK,CLASS_CAR,18,4
 dfb SIDE_BLACK,CLASS_TANK,17,5
 dfb SIDE_BLACK,CLASS_CAR,18,5
 dfb SIDE_BLACK,CLASS_CRUISER,16,6
 dfb SIDE_BLACK,CLASS_CAR,17,6
 dfb SIDE_BLACK,CLASS_CAR,16,7
 dfb SIDE_BLACK,CLASS_TANK,17,7
 dfb SIDE_BLACK,CLASS_CAR,18,7
 dfb $FF

* Board 6
board_map_6
 asc 'wwwwbbggwwwwbbbbwwww'
 asc 'wwwwgggbwwwwbbggwwww'
 asc 'wwwwbbbbwwwwgggbwwww'
 asc 'wwwwbbbbwwwwbbbbwwww'
 asc 'bbgbwwwwppppwwwwbbbg'
 asc 'bggbwwwwppppwwwwbbgg'
 asc 'bgbbwwwwppppwwwwbbgb'
 asc 'wwwwbbbbwwwwbbbbwwww'
 asc 'wwwwggbbwwwwbgggwwww'
 asc 'wwwwbgggwwwwggbbwwww'
 asc 'wwwwbbbbwwwwbbbbwwww'
board_units_6
 dfb SIDE_RED,CLASS_CAR,0,0
 dfb SIDE_RED,CLASS_TANK,1,0
 dfb SIDE_RED,CLASS_CAR,2,0
 dfb SIDE_RED,CLASS_TANK,0,1
 dfb SIDE_RED,CLASS_CRUISER,1,1
 dfb SIDE_RED,CLASS_CAR,2,1
 dfb SIDE_RED,CLASS_CAR,1,2
 dfb SIDE_BLACK,CLASS_CAR,17,8
 dfb SIDE_BLACK,CLASS_CAR,18,8
 dfb SIDE_BLACK,CLASS_TANK,19,8
 dfb SIDE_BLACK,CLASS_CAR,17,9
 dfb SIDE_BLACK,CLASS_CRUISER,18,9
 dfb SIDE_BLACK,CLASS_TANK,19,9
 dfb SIDE_BLACK,CLASS_CAR,17,10
 dfb SIDE_BLACK,CLASS_TANK,18,10
 dfb SIDE_BLACK,CLASS_CAR,19,10
 dfb $FF

* Board 7
board_map_7
 asc 'wwwwwwwwwwwwwwwwwwww'
 asc 'wwwwwwwwwwwwwwwwwwww'
 asc 'wwwwwwwwwbbwwwwwwwww'
 asc 'wwwwwwwwwbbwwwwwwwww'
 asc 'wwwwwwwwwyywwwwwwwww'
 asc 'wwwwwwbbbyybbbwwwwww'
 asc 'wwwwwwwwwyywwwwwwwww'
 asc 'wwwwwwwwwbbwwwwwwwww'
 asc 'wwwwwwwwwbbwwwwwwwww'
 asc 'wwwwwwwwwwwwwwwwwwww'
 asc 'wwwwwwwwwwwwwwwwwwww'
board_units_7
 dfb SIDE_RED,CLASS_CAR,0,3
 dfb SIDE_BLACK,CLASS_CAR,19,3
 dfb SIDE_RED,CLASS_TANK,0,4
 dfb SIDE_RED,CLASS_CAR,1,4
 dfb SIDE_BLACK,CLASS_CAR,18,4
 dfb SIDE_BLACK,CLASS_TANK,19,4
 dfb SIDE_RED,CLASS_CRUISER,0,5
 dfb SIDE_RED,CLASS_TANK,1,5
 dfb SIDE_RED,CLASS_CAR,2,5
 dfb SIDE_BLACK,CLASS_CAR,17,5
 dfb SIDE_BLACK,CLASS_TANK,18,5
 dfb SIDE_BLACK,CLASS_CRUISER,19,5
 dfb SIDE_RED,CLASS_CAR,1,6
 dfb SIDE_BLACK,CLASS_CAR,18,6
 dfb SIDE_BLACK,CLASS_TANK,19,6
 dfb SIDE_BLACK,CLASS_CAR,19,7
 dfb $FF

* Board 8
board_map_8
 asc 'bbbbbbbbbbbbbbbbbbbb'
 asc 'bbbbbbbwwwwwwbbbbbbb'
 asc 'bbbbbwwwwwwwwwwbbbbb'
 asc 'bbbbwwwwwwwwwwwwbbbb'
 asc 'bbbwwwwwwbbwwwwwwbbb'
 asc 'bbwwwwwwbbbbwwwwwwbb'
 asc 'bbbwwwwwwbbwwwwwwbbb'
 asc 'bbbbwwwwwwwwwwwwbbbb'
 asc 'bbbbbwwwwwwwwwwbbbbb'
 asc 'bbbbbbbwwwwwwbbbbbbb'
 asc 'bbbbbbbbbbbbbbbbbbbb'
board_units_8
 dfb SIDE_RED,CLASS_CAR,4,3
 dfb SIDE_BLACK,CLASS_CAR,15,3
 dfb SIDE_RED,CLASS_TANK,3,4
 dfb SIDE_RED,CLASS_CAR,4,4
 dfb SIDE_BLACK,CLASS_CAR,15,4
 dfb SIDE_BLACK,CLASS_TANK,16,4
 dfb SIDE_RED,CLASS_CRUISER,2,5
 dfb SIDE_RED,CLASS_TANK,3,5
 dfb SIDE_RED,CLASS_CAR,4,5
 dfb SIDE_BLACK,CLASS_CAR,15,5
 dfb SIDE_BLACK,CLASS_TANK,16,5
 dfb SIDE_BLACK,CLASS_CRUISER,17,5
 dfb SIDE_RED,CLASS_CAR,4,6
 dfb SIDE_BLACK,CLASS_CAR,15,6
 dfb SIDE_BLACK,CLASS_TANK,16,6
 dfb SIDE_BLACK,CLASS_CAR,15,7
 dfb $FF

* Board 9
board_map_9
 asc 'gwgwgwgwgwwgwgwgwgwg'
 asc 'wgwgwgwgwggwgwgwgwgw'
 asc 'gwgwgwgwgppgwgwgwgwg'
 asc 'wgwgwgwgwggwgwgwgwgw'
 asc 'gwgwgwgwgppgwgwgwgwg'
 asc 'wgwgwgwgwggwgwgwgwgw'
 asc 'gwgwgwgwgppgwgwgwgwg'
 asc 'wgwgwgwgwggwgwgwgwgw'
 asc 'gwgwgwgwgppgwgwgwgwg'
 asc 'wgwgwgwgwggwgwgwgwgw'
 asc 'gwgwgwgwgwwgwgwgwgwg'
board_units_9
 dfb SIDE_RED,CLASS_CAR,2,3
 dfb SIDE_BLACK,CLASS_CAR,17,3
 dfb SIDE_RED,CLASS_TANK,1,4
 dfb SIDE_RED,CLASS_CAR,3,4
 dfb SIDE_BLACK,CLASS_CAR,16,4
 dfb SIDE_BLACK,CLASS_TANK,18,4
 dfb SIDE_RED,CLASS_CRUISER,0,5
 dfb SIDE_RED,CLASS_TANK,2,5
 dfb SIDE_RED,CLASS_CAR,4,5
 dfb SIDE_BLACK,CLASS_CAR,15,5
 dfb SIDE_BLACK,CLASS_TANK,17,5
 dfb SIDE_BLACK,CLASS_CRUISER,19,5
 dfb SIDE_RED,CLASS_CAR,3,6
 dfb SIDE_BLACK,CLASS_CAR,16,6
 dfb SIDE_BLACK,CLASS_TANK,18,6
 dfb SIDE_BLACK,CLASS_CAR,17,7
 dfb $FF

* Board 10
board_map_10
 asc 'TTTTTTT~TTT.MM...TTT'
 asc 'TTTTT.=~T.MMMMTTT.TT'
 asc 'TTTT.T~=.MMMMTTTTT.T'
 asc 'TTT.TT~T.MMMMTTTTT.T'
 asc 'TTT.TT~~~.MMMTTTTT.T'
 asc 'TTTT.TTT~=MMMMTTT.TT'
 asc 'MTTTT...=~MMMMTT.TTT'
 asc 'MMTTTT.TT~~~~~T.TTTT'
 asc 'MMMTTTT.TTT~~~=TTTTT'
 asc 'MMMMTTTT.TTTT=~TTTTT'
 asc 'MMMMMTTTT....T~~TTTT'
board_units_10
 dfb SIDE_BLACK,CLASS_CAR,14,1
 dfb SIDE_RED,CLASS_CAR,2,2
 dfb SIDE_BLACK,CLASS_TANK,13,2
 dfb SIDE_BLACK,CLASS_CAR,14,2
 dfb SIDE_RED,CLASS_TANK,1,3
 dfb SIDE_RED,CLASS_CAR,2,3
 dfb SIDE_BLACK,CLASS_CRUISER,13,3
 dfb SIDE_BLACK,CLASS_TANK,14,3
 dfb SIDE_RED,CLASS_CRUISER,0,4
 dfb SIDE_RED,CLASS_TANK,1,4
 dfb SIDE_RED,CLASS_CAR,2,4
 dfb SIDE_BLACK,CLASS_TANK,13,4
 dfb SIDE_BLACK,CLASS_CAR,14,4
 dfb SIDE_RED,CLASS_CAR,1,5
 dfb SIDE_BLACK,CLASS_CAR,14,5
 dfb SIDE_BLACK,CLASS_CAR,14,6
 dfb $FF
