*----------------------------------------------------------
* sound_samples.s - sizes, DOC size codes, playback
* frequencies and blob offsets for Combat Chess's POKEY
* effects, ripped from the Atari original. The waveform
* bytes are in the SOUNDS disk file (res/sounds.bin), loaded
* at game start. GENERATED by tools/gen_sound.py (a port of
* atari800's Ron Fries POKEY engine). Do not edit.
*----------------------------------------------------------
snd_move_wave_size = 8191
snd_move_wave_code = 5
snd_move_wave_freq = $0093
snd_move_wave_off  = 0
snd_move_wave_frames = 65
snd_fire_wave_size = 1023
snd_fire_wave_code = 2
snd_fire_wave_freq = $018F
snd_fire_wave_off  = 8192
snd_fire_wave_frames = 3
snd_explode_wave_size = 16383
snd_explode_wave_code = 6
snd_explode_wave_freq = $00C9
snd_explode_wave_off  = 9216
snd_explode_wave_frames = 95
snd_blob_size = 25600
